AllCops:
  TargetRubyVersion: 3.3.0
  Exclude:
    - "db/migrate/*.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
