AllCops:
  TargetRubyVersion: 3.3.0
  Exclude:
    - "db/migrate/*.rb"
    - "db/schema.rb"

Metrics/BlockLength:
  Exclude:
    - "config/initializers/simple_form.rb"
    - "spec/**/*.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
